// Code generated by ObjectBox; DO NOT EDIT.

#pragma once

#include <cstdbool>
#include <cstdint>

#include "flatbuffers/flatbuffers.h"
#include "objectbox.h"
#include "objectbox.hpp"


struct Document_;

struct Document {
    obx_id id;
    std::string text;
    std::string source;
    /// BAAI/bge-m3 输出 1024 维向量，使用余弦相似度做 HNSW 近似最近邻检索。
    std::vector<float> embedding;

    struct _OBX_MetaInfo {
        static constexpr obx_schema_id entityId() { return 1; }
    
        static void setObjectId(Document& object, obx_id newId) { object.id = newId; }
    
        /// Write given object to the FlatBufferBuilder
        static void toFlatBuffer(flatbuffers::FlatBufferBuilder& fbb, const Document& object);
    
        /// Read an object from a valid FlatBuffer
        static Document fromFlatBuffer(const void* data, size_t size);
    
        /// Read an object from a valid FlatBuffer
        static std::unique_ptr<Document> newFromFlatBuffer(const void* data, size_t size);
    
        /// Read an object from a valid FlatBuffer
        static void fromFlatBuffer(const void* data, size_t size, Document& outObject);
    };
};

struct Document_ {
    static const obx::Property<Document, OBXPropertyType_Long> id;
    static const obx::Property<Document, OBXPropertyType_String> text;
    static const obx::Property<Document, OBXPropertyType_String> source;
    static const obx::Property<Document, OBXPropertyType_FloatVector> embedding;
};

