// Code generated by ObjectBox; DO NOT EDIT.

#include "document.obx.hpp"

const obx::Property<Document, OBXPropertyType_Long> Document_::id(1);
const obx::Property<Document, OBXPropertyType_String> Document_::text(2);
const obx::Property<Document, OBXPropertyType_String> Document_::source(3);
const obx::Property<Document, OBXPropertyType_FloatVector> Document_::embedding(4);

void Document::_OBX_MetaInfo::toFlatBuffer(flatbuffers::FlatBufferBuilder& fbb, const Document& object) {
    fbb.Clear();
    auto offsettext = fbb.CreateString(object.text);
    auto offsetsource = fbb.CreateString(object.source);
    auto offsetembedding = fbb.CreateVector(object.embedding);
    flatbuffers::uoffset_t fbStart = fbb.StartTable();
    fbb.AddElement(4, object.id);
    fbb.AddOffset(6, offsettext);
    fbb.AddOffset(8, offsetsource);
    fbb.AddOffset(10, offsetembedding);
    flatbuffers::Offset<flatbuffers::Table> offset;
    offset.o = fbb.EndTable(fbStart);
    fbb.Finish(offset);
}

Document Document::_OBX_MetaInfo::fromFlatBuffer(const void* data, size_t size) {
    Document object;
    fromFlatBuffer(data, size, object);
    return object;
}

std::unique_ptr<Document> Document::_OBX_MetaInfo::newFromFlatBuffer(const void* data, size_t size) {
    auto object = std::make_unique<Document>();
    fromFlatBuffer(data, size, *object);
    return object;
}

void Document::_OBX_MetaInfo::fromFlatBuffer(const void* data, size_t, Document& outObject) {
    const auto* table = flatbuffers::GetRoot<flatbuffers::Table>(data);
    assert(table);
    outObject.id = table->GetField<obx_id>(4, 0);
    {
        auto* ptr = table->GetPointer<const flatbuffers::String*>(6);
        if (ptr) {
            outObject.text.assign(ptr->c_str(), ptr->size());
        } else {
            outObject.text.clear();
        }
    }
    {
        auto* ptr = table->GetPointer<const flatbuffers::String*>(8);
        if (ptr) {
            outObject.source.assign(ptr->c_str(), ptr->size());
        } else {
            outObject.source.clear();
        }
    }
    {
        auto* ptr = table->GetPointer<const flatbuffers::Vector<float>*>(10);
        if (ptr) { 
            outObject.embedding.assign(ptr->begin(), ptr->end());
        } else {
            outObject.embedding.clear();
        }
    }
}

